### ISSUE TITLE
Environment config not working

### ISSUE THREAD

**Issue by Wishdream** [codetheweb/aoede#24] opened 2022-08-11 04:22 UTC
I'm currently using the docker-compose given via portainer
and provides the following error:
```log
Couldn't read config
Missing field: 'DISCORD_TOKEN'
```

All my environment vars are set and just following the provided docker-compose file:
```yaml
version: '3.4'

services:
  aoede:
    image: codetheweb/aoede
    restart: always
    volumes:
      - ./aoede:/data
    environment:
      - DISCORD_TOKEN=discord.token.here
      - SPOTIFY_USERNAME=spotitest
      - SPOTIFY_PASSWORD=notarealpassword
      - DISCORD_USER_ID=targeteduserIDhere
```

I think it's trying to read the config.toml where it shouldn't exist or somehow got bundled with the docker image

**Comment by nodgear** [comment] 2022-08-12 00:35
This issue seems to be related to the fix attempt by on #15 
This was partially reported on #14

**Comment by cloudybyte** [comment] 2022-08-12 11:53
Yeah, I think the problem got introduced in #18.
Serdes rename macro somehow messes with figments ability to deserialize the config properly. 
I was able to reproduce this issue and fix it by removing the macro.

The easiest way to fix this would probably be ditching figment all together and moving towards [dotenv](https://lib.rs/crates/dotenv) (and relying on a `.env` file or env vars for configuration). What do you think @codetheweb?

**Comment by cloudybyte** [comment] 2022-08-12 12:51
The issues are not related btw :)

**Comment by cloudybyte** [comment] 2022-08-12 16:09
#25 should fix your issue @Wishdream.
Please wait until a build for [87dc75e](https://github.com/cloudybyte/aoede/commit/87dc75e9ae30e39fd0a84bbf6000b7e724f7cd89) is published (or build it yourself if you're able to) and try the fix

<br>

---

> The easiest way to fix this would probably be ditching figment all together and moving towards [dotenv](https://lib.rs/crates/dotenv) (and relying on a `.env` file or env vars for configuration). What do you think @codetheweb?

I don't know if thats really required. I don't really like the fix(#25) though.

**Comment by Wishdream** [comment] 2022-08-13 01:14
> #25 should fix your issue @Wishdream. Please wait until a build for [87dc75e](https://github.com/cloudybyte/aoede/commit/87dc75e9ae30e39fd0a84bbf6000b7e724f7cd89) is published (or build it yourself if you're able to) and try the fix
Going to build it myself for now, at least until there's an agreed-upon fix.
Not exactly resolved yet so I'll keep this open for now.

**Comment by cloudybyte** [comment] 2022-08-13 01:20
Well, I can't merge into the main repo, thats why the fix isn't official yet.
Can you confirm it worked for you?

**Comment by codetheweb** [comment] 2022-08-13 17:42
I would rather use `.env` over `.toml` but no strong preference.

**Closed** 2022-08-13 18:44 UTC
