### ISSUE TITLE
 My cmd says that can't read the config file

### ISSUE THREAD

**Issue by xKingsito** [codetheweb/aoede#15] opened 2022-06-30 12:41 UTC

**Comment by codetheweb** [comment] 2022-07-02 16:55
Could you please provide more details? What's the full output?

**Comment by nodgear** [comment] 2022-07-21 01:17
I know what his issue is:
He's running Aoede built from source.
When building from source i got the same result when running aoede, it would say my `config.toml` file is nowhere to be found (Arch linux x64)

**Comment by codetheweb** [comment] 2022-07-26 23:53
It might be expecting `config.toml` to be next to the binary in `target/debug` or `target/release`.

**Comment by nodgear** [comment] 2022-07-28 23:29
Not the case either.
![image](https://user-images.githubusercontent.com/22383863/181653496-bb1c9c89-8bba-4217-8714-b544198e8f85.png)

**Comment by codetheweb** [comment] 2022-08-03 18:04
It's not working for me either.

@cloudybyte any ideas why it's not working?

**Comment by cloudybyte** [comment] 2022-08-03 18:56
Could you please show us your config file?

**Comment by nodgear** [comment] 2022-08-03 23:31
> Could you please show us your config file? pls censor the tokens ofc
```
DISCORD_TOKEN="<CENSORED>.<CENSORED>.<CENSORED>"
SPOTIFY_USERNAME="3a3a4glj34s40sw2ppvd1642l"
SPOTIFY_PASSWORD="<CENSORED>"
DISCORD_USER_ID="<CENSORED>"
```

**Comment by cloudybyte** [comment] 2022-08-04 10:21
Mhm that sounds weird and is definitely a bug. I was able to reproduce it though, so not totally bad news.
I'll look into it

**Comment by cloudybyte** [comment] 2022-08-04 12:55
should be fixed in #18.
can you please confirm the fix @nodgear?

**Comment by codetheweb** [comment] 2022-08-09 02:36
This should be fixed in v0.4.1, please try it out when you get a chance. :)

**Comment by jacksight** [comment] 2022-08-10 14:57
I got this issue,too. I'm using v0.4.1 currently

**Comment by nodgear** [comment] 2022-08-10 17:32
> I got this issue,too. I'm using v0.4.1 currently

Have you moved the config file to the same place where the binary is?

**Comment by cloudybyte** [comment] 2022-08-11 20:01
Did the fix work for you @nodgear?

**Comment by nodgear** [comment] 2022-08-12 00:16
I will be testing right now, had no time to test previously

**Comment by cloudybyte** [comment] 2022-08-12 12:53
Oops I forgot to change the sample config after the patch.
You need to remove the quotes around the user id

**Comment by jacksight** [comment] 2022-08-12 14:08
I open the aoede file on my mac, and then it opens the terminal, and my config.toml is in the release folder. When I execute it, it says:
Couldn't read config
Missing field: 'DISCORD_TOKEN'

Saving session...completed.

I don't know what happened...

This is my config file:
DISCORD_TOKEN= xxxxxxxxxxxxxxxxxxxxxxxx
SPOTIFY_USERNAME= xxxxxxxx@xxxxx.com
SPOTIFY_PASSWORD= xxxxxxxxx
DISCORD_USER_ID= xxxxxxxxxxxxxx

**Comment by cloudybyte** [comment] 2022-08-12 15:40
The config is supposed to look like this:
```toml
DISCORD_TOKEN="Mjk3ODQzNDgzNzgzODU2MjMw.SxDNko.UOdRWlDuz_lFrTOeQWEuzKGBmDFdVTGns3jd4o"
SPOTIFY_USERNAME="mail@example.com"
SPOTIFY_PASSWORD="MySpotifyPassword"
DISCORD_USER_ID=301780655019130880
```

**Comment by jacksight** [comment] 2022-08-13 04:47
I've tried both ways, it's not working

**Comment by cloudybyte** [comment] 2022-08-13 08:54
Well, can you provide error logs? Please copy paste the example config above and only replace the values in there. Leave the quotes as they are.

**Comment by jacksight** [comment] 2022-08-13 08:59
`DISCORD_TOKEN="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
SPOTIFY_USERNAME="xxxxxxxxxxxx@hotmail.com"
SPOTIFY_PASSWORD="xxxxxxxxxxxxxxx"
DISCORD_USER_ID=476622988385714176
`

**Comment by jacksight** [comment] 2022-08-17 02:52
So...... What seems to be the problem?

**Comment by codetheweb** [comment] 2022-08-18 02:18
That looks right to me. Are you able to try passing in via the environment instead?

**Closed** 2022-12-06 16:33 UTC
Labels: bug

**Comment by Knopfi02** [comment] 2023-06-25 19:31
same problem :(

**Comment by cloudybyte** [comment] 2023-06-27 12:05
Are you using a mac as well? @Knopfi02

**Comment by Knopfi02** [comment] 2023-06-27 19:35
No, I'm on windows @cloudybyte

**Comment by cloudybyte** [comment] 2023-06-28 03:44
Are you executing the binary via double-clicking it? If yes, please try opening via command line/powershell.
Note: you need to be in aoedes root directory for this to work.

**Comment by j0uns** [comment] 2025-07-03 10:20
> DISCORD_TOKEN="Mjk3ODQzNDgzNzgzODU2MjMw.SxDNko.UOdRWlDuz_lFrTOeQWEuzKGBmDFdVTGns3jd4o"
> SPOTIFY_USERNAME="mail@example.com"
> SPOTIFY_PASSWORD="MySpotifyPassword"
> DISCORD_USER_ID=301780655019130880

perhaps it makes sense to add this format-information to the readme or faq. I had to search for the information for a long time.

**Comment by oleggtro** [comment] 2025-07-08 20:37
Hey,

please redact your discord token from the issue (and invalidate/regenerate it as fast as possible).

**Comment by j0uns** [comment] 2025-07-09 07:20
> Hey,
> 
> please redact your discord token from the issue (and invalidate/regenerate it as fast as possible).

i just quoted your message from [Aug 12, 2022](https://github.com/codetheweb/aoede/issues/15#issuecomment-1213248627)
